#!/bin/sh

# Backend
cd backend
cargo fmt

# Frontend
cd ../frontend
npm run lint -- --fix > /dev/null 2>&1
npx prettier --write . > /dev/null 2>&1

# Add the changed files to the commit
cd ..
git add --update
