#!/bin/sh

# Backend
cd backend
cargo fmt

# Frontend
cd ../frontend
npm run lint -- --fix > /dev/null
npx prettier --write . > /dev/null

# Add the changed files to the commit
cd ..
git add --update
