name: Backend CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  code_quality_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: cargo check
        run: cargo check --all
        working-directory: backend

      - name: cargo fmt check
        run: cargo fmt --all --check
        working-directory: backend

      - name: cargo test
        run: cargo test --all
        working-directory: backend

      - name: cargo clippy check
        run: cargo clippy --all --all-targets --all-features
        working-directory: backend
