name: Rust CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  code_quality_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Change to backend directory
        run: cd backend

      - name: cargo check
        run: cargo check --all

      - name: cargo fmt check
        run: cargo fmt --all --check

      - name: cargo test
        run: cargo test --all

      - name: cargo clippy check
        run: cargo clippy --all --all-targets --all-features