name: Server CD
on:
  workflow_run:
    workflows: ["backend_ci", "frontend_ci"]
    types: [completed]
    # branches: ["main", "*"]


jobs:
  auto_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: build backend
        run: cargo build --release
        working-directory: backend

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: build frontend
        run: |
          npm ci
          npm run build
        working-directory: frontend

      - name: package artifacts
        run: |
          mkdir -p artifacts
          cp backend/target/release/backend artifacts
          cp -r frontend/out artifacts
          tar czvf deployment.tar.gz artifacts

      - name: upload artifacts
        uses: actions/upload-artifacts@v3
        with:
          name: deployment
          path: deployment.tar.gz

